# Data Cleaning

### The dataset contained missing values, inconsistent formatting, and missing entries.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"C:\Users\Mika-iel Osman\OneDrive\Documents\Cleaning Data\dirty_cafe_sales.csv")

In [4]:
pd.set_option('display.max_rows', None)

In [5]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [7]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [8]:
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [9]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [14]:
df['item'] = df['item'].str.strip().str.lower().fillna('unknown').str.replace('error' , 'unknown' )
df['item'].unique()

array(['coffee', 'cake', 'cookie', 'salad', 'smoothie', 'unknown',
       'sandwich', 'juice', 'tea'], dtype=object)

In [139]:
df['quantity'] = pd.to_numeric(df['quantity'].astype(str).str.strip().str.replace(r'[^\d.]','', regex=True),errors = 'coerce')
df['quantity'] = df['quantity'].astype('Int64')

In [17]:
df['price_per_unit'] = pd.to_numeric(df['price_per_unit'].astype(str).str.strip().str.replace(r'[^\d.]','', regex=True),errors = 'coerce')

array([2. , 3. , 1. , 5. , 4. , 1.5, nan])

In [18]:
df['total_spent'] = pd.to_numeric(df['total_spent'].astype(str).str.strip().str.replace(r'[^\d.]','', regex=True),errors = 'coerce')

array([ 4. , 12. ,  nan, 10. , 20. ,  9. , 16. , 15. , 25. ,  8. ,  5. ,
        3. ,  6. ,  2. ,  1. ,  7.5,  4.5,  1.5])

In [19]:
df['payment_method'] = df['payment_method'].str.lower().replace('error','unknown')

array(['credit card', 'cash', 'unknown', 'digital wallet', nan],
      dtype=object)

In [20]:
df['location'] = df['location'].str.lower().str.replace('error','unknown')

array(['takeaway', 'in-store', 'unknown', nan], dtype=object)

In [22]:
df['transaction_date'] = df['transaction_date'].str.lower().str.replace('error','unknown').fillna('unknown')
df['transaction_date'] = df['transaction_date'].replace('unknown', np.nan)
df['transaction_date'] = pd.to_datetime(df['transaction_date'], errors = 'coerce')

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9946 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    9946 non-null   object
 1   item              9946 non-null   object
 2   quantity          9926 non-null   Int64
 3   price_per_unit    9946 non-null   float64
 4   total_spent       9447 non-null   float64
 5   payment_method    7384 non-null   object
 6   location          6704 non-null   object
 7   transaction_date  9489 non-null   datetime64[ns]
dtypes: Int64(1), datetime64[ns](1), float64(2), object(4)
memory usage: 967.1+ KB

In [145]:
# check if the 'price_per_unit is correct throughout the sheet, if not change it
# coffee = 2 ; cake = 3; cookie = 1; salad = 5; smoothie = 4; sandwich = 4 ; juice = 3 ; tea = 1.5 
# fill in uknowns as well for items

price_map = {'coffee': 2, 'cake': 3, 'cookie': 1, 'salad': 5, 'smoothie': 4, 'sandwich': 4, 'juice': 3, 'tea': 1.5}
df['correct_price'] = df['item'].map(price_map)
df['is_correct'] = df['price_per_unit'] == df['correct_price']

# double check and fillna in 'price_per_unit' with the 'correct_price'
# df[(df['is_correct'] == False) & (df['item'] != 'unknown')][['item', 'price_per_unit', 'correct_price', 'is_correct']]
df['price_per_unit'] = df['price_per_unit'].fillna(df['correct_price'])
 

#to_drop = df[(df['item'] == 'unknown') & (df['price_per_unit'].isna())].index
#df = df.drop(to_drop)


#or drop columns here
#df = df.drop(df.columns[8:], axis = 1)

In [93]:
# fill in unknown 'item' where possible

price_map2 = { 2 :'coffee', 1 :'cookie', 5 : 'salad', 1.5 :'tea'}
df['correct_item'] = df['price_per_unit'].map(price_map2)
indexes_to_correct = df[(df['item'] == 'unknown') & (df['correct_item'].notna())][['item','correct_item']].index
df.loc[indexes_to_correct, 'item'] = df.loc[indexes_to_correct, 'correct_item']

         item correct_item
6     unknown          NaN
8     unknown          NaN
36    unknown          NaN
61    unknown          NaN
69    unknown          NaN
91    unknown          NaN
153   unknown          NaN
165   unknown          NaN
168   unknown          NaN
184   unknown          NaN
197   unknown          NaN
203   unknown          NaN
216   unknown          NaN
227   unknown          NaN
235   unknown          NaN
249   unknown          NaN
258   unknown          NaN
269   unknown          NaN
288   unknown          NaN
323   unknown          NaN
356   unknown          NaN
362   unknown          NaN
366   unknown          NaN
369   unknown          NaN
372   unknown          NaN
386   unknown          NaN
402   unknown          NaN
434   unknown          NaN
442   unknown          NaN
476   unknown          NaN
479   unknown          NaN
482   unknown          NaN
511   unknown          NaN
535   unknown          NaN
551   unknown          NaN
552   unknown          NaN
602   unknown          NaN
605   unknown          NaN
647   unknown          NaN
679   unknown          NaN
688   unknown          NaN
727   unknown          NaN
746   unknown          NaN
759   unknown          NaN
769   unknown          NaN
797   unknown          NaN
805   unknown          NaN
806   unknown          NaN
815   unknown          NaN
880   unknown          NaN
881   unknown          NaN
901   unknown          NaN
903   unknown          NaN
919   unknown          NaN
929   unknown          NaN
975   unknown          NaN
987   unknown          NaN
990   unknown          NaN
1019  unknown          NaN
1024  unknown          NaN
1045  unknown          NaN
1063  unknown          NaN
1077  unknown          NaN
1099  unknown          NaN
1127  unknown          NaN
1282  unknown          NaN
1296  unknown          NaN
1329  unknown          NaN
1339  unknown          NaN
1351  unknown          NaN
1364  unknown          NaN
1375  unknown          NaN
1386  unknown          NaN
1420  unknown          NaN
1430  unknown          NaN
1486  unknown          NaN
1522  unknown          NaN
1614  unknown          NaN
1615  unknown          NaN
1629  unknown          NaN
1641  unknown          NaN
1678  unknown          NaN
1703  unknown          NaN
1719  unknown          NaN
1746  unknown          NaN
1790  unknown          NaN
1796  unknown          NaN
1803  unknown          NaN
1889  unknown          NaN
1913  unknown          NaN
1919  unknown          NaN
1943  unknown          NaN
1959  unknown          NaN
1962  unknown          NaN
2016  unknown          NaN
2107  unknown          NaN
2139  unknown          NaN
2150  unknown          NaN
2156  unknown          NaN
2174  unknown          NaN
2218  unknown          NaN
2222  unknown          NaN
2239  unknown          NaN
2254  unknown          NaN
2280  unknown          NaN
2287  unknown          NaN
2302  unknown          NaN
2327  unknown          NaN
2371  unknown          NaN
2380  unknown          NaN
2383  unknown          NaN
2388  unknown          NaN
2516  unknown          NaN
2557  unknown          NaN
2563  unknown          NaN
2583  unknown          NaN
2587  unknown          NaN
2656  unknown          NaN
2674  unknown          NaN
2712  unknown          NaN
2731  unknown          NaN
2787  unknown          NaN
2802  unknown          NaN
2817  unknown          NaN
2821  unknown          NaN
2842  unknown          NaN
2859  unknown          NaN
2904  unknown          NaN
2907  unknown          NaN
2934  unknown          NaN
2947  unknown          NaN
2968  unknown          NaN
2969  unknown          NaN
2978  unknown          NaN
3010  unknown          NaN
3017  unknown          NaN
3059  unknown          NaN
3067  unknown          NaN
3079  unknown          NaN
3115  unknown          NaN
3146  unknown          NaN
3149  unknown          NaN
3172  unknown          NaN
3175  unknown          NaN
3191  unknown          NaN
3200  unknown          NaN
3210  unknown          NaN
3227  unknown          NaN
3239  unknown          NaN
3243  unknown          NaN
3262  unknown          NaN
3354  unknown          NaN
3367  unknown          NaN
3374  unknown          NaN
3375  unknown          NaN
3378  unknown          NaN
3396  unknown          NaN
3427  unknown          NaN
3444  unknown          NaN
3445  unknown          NaN
3446  unknown          NaN
3468  unknown          NaN
3479  unknown          NaN
3498  unknown          NaN
3545  unknown          NaN
3575  unknown          NaN
3643  unknown          NaN
3649  unknown          NaN
3656  unknown          NaN
3658  unknown          NaN
3659  unknown          NaN
3662  unknown          NaN
3705  unknown          NaN
3717  unknown          NaN
3730  unknown          NaN
3805  unknown          NaN
3824  unknown          NaN
3877  unknown          NaN
3913  unknown          NaN
3921  unknown          NaN
3945  unknown          NaN
3974  unknown          NaN
3991  unknown          NaN
4003  unknown          NaN
4018  unknown          NaN
4086  unknown          NaN
4093  unknown          NaN
4115  unknown          NaN
4116  unknown          NaN
4119  unknown          NaN
4211  unknown          NaN
4215  unknown          NaN
4233  unknown          NaN
4249  unknown          NaN
4255  unknown          NaN
4279  unknown          NaN
4300  unknown          NaN
4306  unknown          NaN
4319  unknown          NaN
4324  unknown          NaN
4327  unknown          NaN
4412  unknown          NaN
4421  unknown          NaN
4430  unknown          NaN
4445  unknown          NaN
4456  unknown          NaN
4473  unknown          NaN
4528  unknown          NaN
4566  unknown          NaN
4596  unknown          NaN
4649  unknown          NaN
4651  unknown          NaN
4656  unknown          NaN
4665  unknown          NaN
4701  unknown          NaN
4736  unknown          NaN
4737  unknown          NaN
4797  unknown          NaN
4806  unknown          NaN
4807  unknown          NaN
4831  unknown          NaN
4838  unknown          NaN
4842  unknown          NaN
4853  unknown          NaN
4872  unknown          NaN
4875  unknown          NaN
4906  unknown          NaN
4909  unknown          NaN
4915  unknown          NaN
4927  unknown          NaN
4939  unknown          NaN
4985  unknown          NaN
4995  unknown          NaN
5014  unknown          NaN
5045  unknown          NaN
5106  unknown          NaN
5114  unknown          NaN
5119  unknown          NaN
5125  unknown          NaN
5197  unknown          NaN
5213  unknown          NaN
5216  unknown          NaN
5245  unknown          NaN
5250  unknown          NaN
5262  unknown          NaN
5300  unknown          NaN
5406  unknown          NaN
5450  unknown          NaN
5460  unknown          NaN
5488  unknown          NaN
5489  unknown          NaN
5517  unknown          NaN
5550  unknown          NaN
5576  unknown          NaN
5580  unknown          NaN
5628  unknown          NaN
5657  unknown          NaN
5661  unknown          NaN
5669  unknown          NaN
5714  unknown          NaN
5743  unknown          NaN
5765  unknown          NaN
5813  unknown          NaN
5817  unknown          NaN
5820  unknown          NaN
5822  unknown          NaN
5824  unknown          NaN
5851  unknown          NaN
5872  unknown          NaN
5892  unknown          NaN
5895  unknown          NaN
5928  unknown          NaN
5933  unknown          NaN
5961  unknown          NaN
6087  unknown          NaN
6092  unknown          NaN
6120  unknown          NaN
6136  unknown          NaN
6166  unknown          NaN
6171  unknown          NaN
6192  unknown          NaN
6205  unknown          NaN
6224  unknown          NaN
6262  unknown          NaN
6264  unknown          NaN
6265  unknown          NaN
6292  unknown          NaN
6302  unknown          NaN
6358  unknown          NaN
6368  unknown          NaN
6418  unknown          NaN
6434  unknown          NaN
6443  unknown          NaN
6447  unknown          NaN
6482  unknown          NaN
6488  unknown          NaN
6500  unknown          NaN
6507  unknown          NaN
6508  unknown          NaN
6510  unknown          NaN
6534  unknown          NaN
6592  unknown          NaN
6595  unknown          NaN
6605  unknown          NaN
6640  unknown          NaN
6641  unknown          NaN
6692  unknown          NaN
6693  unknown          NaN
6768  unknown          NaN
6822  unknown          NaN
6867  unknown          NaN
6873  unknown          NaN
6899  unknown          NaN
6910  unknown          NaN
6932  unknown          NaN
6988  unknown          NaN
7004  unknown          NaN
7028  unknown          NaN
7067  unknown          NaN
7091  unknown          NaN
7093  unknown          NaN
7135  unknown          NaN
7187  unknown          NaN
7188  unknown          NaN
7226  unknown          NaN
7227  unknown          NaN
7282  unknown          NaN
7307  unknown          NaN
7310  unknown          NaN
7340  unknown          NaN
7373  unknown          NaN
7377  unknown          NaN
7388  unknown          NaN
7403  unknown          NaN
7410  unknown          NaN
7418  unknown          NaN
7452  unknown          NaN
7463  unknown          NaN
7551  unknown          NaN
7604  unknown          NaN
7615  unknown          NaN
7624  unknown          NaN
7627  unknown          NaN
7684  unknown          NaN
7732  unknown          NaN
7800  unknown          NaN
7804  unknown          NaN
7819  unknown          NaN
7853  unknown          NaN
7863  unknown          NaN
7876  unknown          NaN
7877  unknown          NaN
7894  unknown          NaN
7897  unknown          NaN
7943  unknown          NaN
7951  unknown          NaN
7971  unknown          NaN
8117  unknown          NaN
8134  unknown          NaN
8137  unknown          NaN
8170  unknown          NaN
8203  unknown          NaN
8228  unknown          NaN
8234  unknown          NaN
8277  unknown          NaN
8278  unknown          NaN
8281  unknown          NaN
8351  unknown          NaN
8360  unknown          NaN
8368  unknown          NaN
8376  unknown          NaN
8391  unknown          NaN
8392  unknown          NaN
8407  unknown          NaN
8516  unknown          NaN
8517  unknown          NaN
8528  unknown          NaN
8542  unknown          NaN
8554  unknown          NaN
8568  unknown          NaN
8651  unknown          NaN
8654  unknown          NaN
8671  unknown          NaN
8698  unknown          NaN
8709  unknown          NaN
8731  unknown          NaN
8733  unknown          NaN
8736  unknown          NaN
8761  unknown          NaN
8778  unknown          NaN
8787  unknown          NaN
8788  unknown          NaN
8793  unknown          NaN
8794  unknown          NaN
8883  unknown          NaN
8889  unknown          NaN
8908  unknown          NaN
8933  unknown          NaN
8993  unknown          NaN
9005  unknown          NaN
9011  unknown          NaN
9014  unknown          NaN
9064  unknown          NaN
9089  unknown          NaN
9099  unknown          NaN
9107  unknown          NaN
9117  unknown          NaN
9131  unknown          NaN
9191  unknown          NaN
9208  unknown          NaN
9217  unknown          NaN
9218  unknown          NaN
9238  unknown          NaN
9260  unknown          NaN
9278  unknown          NaN
9284  unknown          NaN
9313  unknown          NaN
9315  unknown          NaN
9360  unknown          NaN
9366  unknown          NaN
9392  unknown          NaN
9427  unknown          NaN
9460  unknown          NaN
9461  unknown          NaN
9469  unknown          NaN
9471  unknown          NaN
9490  unknown          NaN
9497  unknown          NaN
9513  unknown          NaN
9530  unknown          NaN
9582  unknown          NaN
9597  unknown          NaN
9610  unknown          NaN
9616  unknown          NaN
9641  unknown          NaN
9662  unknown          NaN
9727  unknown          NaN
9761  unknown          NaN
9763  unknown          NaN
9771  unknown          NaN
9836  unknown          NaN
9885  unknown          NaN
9910  unknown          NaN
9918  unknown          NaN
9946  unknown          NaN
9981  unknown          NaN
9994  unknown          NaN

In [106]:
# fill in Na and check if the 'total_spent' is correct

df['calculated_tot'] = df['quantity'] * df['price_per_unit']
df['total_spent'] = df[['total_spent']].fillna(df['calculated_tot'])

In [108]:
# drop columns and clear space
df = df.drop(columns = ['correct_price','is_correct','correct_item', 'calculated_tot'])

In [137]:
# fill in missing 'quantity'


df['quantity_calc'] = df['total_spent'] / df['price_per_unit']
#df[(df['quantity'] != df['quantity_calc'])]
#df[df['quantity'].isna()][['quantity','quantity_calc']] 
df['quantity'] = df['quantity'].astype(float)
df['quantity'] = df['quantity'].fillna(df['quantity_calc'])

In [162]:
#check and fill in the 'total_spent'

#df['total_spent_calc'] = df['quantity'] * df['price_per_unit']
#df['total_spent'] = df['total_spent'].fillna(df['total_spent_calc'])
#df[(df['total_spent'] != df['total_spent_calc'])]

#drop column
#df = df.drop('total_spent_calc', axis = 1)

In [165]:
df['location'] = df['location'].fillna('unknown')

In [179]:
# convert Unknowns to na as it is easier to work with
#check

df.isna().sum()
#df = df.replace('unknown', np.nan)

transaction_id        0
item                447
quantity              0
price_per_unit        0
total_spent           0
transaction_date    457
dtype: int64

In [174]:
#dropping na rows in 'quantity' and 'total_spent'
#df = df.dropna(subset=['quantity', 'total_spent'])

In [178]:
df = df.drop(columns = ['payment_method','location'])

In [182]:
df.to_csv(r'C:\Users\Mika-iel Osman\OneDrive\Documents\Cleaning Data\Cleaning_data_completed\Cleaned_cafe_data.csv', index = False)